name: Build PROGPARTPOE

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore PROGPARTPOE.csproj

      - name: Build Project
        run: msbuild PROGPARTPOE.csproj /p:Configuration=Release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: PROGPARTPOE-build
          path: |
            bin/Release
